#!/usr/bin/env php
<?php

use Kos\KosCommand;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';


$application = new Application();
$command = new KosCommand();

$application->add($command);

$application->setDefaultCommand($command->getName(), true);
$application->run();
